### ISSUE TITLE
해당 유저를 찾을 수 없음

### ISSUE THREAD

**Issue by kimgh06** [GSM-MSG/GAuth-Devops#4]
![image](https://github.com/GSM-MSG/GAuth-Devops/assets/101877146/670f394f-f955-4b74-832f-953b89adf8d7)
gauth 로그인 사용중 해당 유저를 찾을 수 없다는 오류가 출력됨.

새롭게 계정을 생성하려고 해도 알 수 없는 오류가 발생됨.
![image](https://github.com/GSM-MSG/GAuth-Devops/assets/101877146/5b9cff27-7d6f-4db5-b180-565dd1bf58b7)

이 때문에 전체적인 서비스를 이용할 수 없음.

**Comment by MinnSeoo** [comment]
클타 서비스가 유료화 되어서 aws로 서비스 마이그레이션 중이여서 발생한 문제 같습니다.

**Comment by MinnSeoo** [comment]
최대한 빠른 시일 내에 복구 시키겠습니다.
